import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "UsersPage",
  description: "Generated by create UsersPage",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}
