import type { Metadata } from "next";
import "./globals.css";
import MenuPage from "./menu/page";


export const metadata: Metadata = {
  title: "Menu",
  description: "Generated by create next app",
};

export default function MenuLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html>
      <body>
      <MenuPage/>
        {children}
      </body>
      </html>
  );
}
